server.port=8080
spring.application.name=week-6-microservices
management.endpoints.web.exposure.include=health,info
app.welcome.message=Welcome to Week 6 microservices learning
inventory.service.url=http://localhost:8081
resilience4j.circuitbreaker.instances.demoService.minimumNumberOfCalls=3
resilience4j.circuitbreaker.instances.demoService.failureRateThreshold=50
